server:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: ${ARGOCD_IRSA_ROLE_ARN}

  extraArgs:
    - --insecure

  service:
    type: LoadBalancer
    port: 80

configs:
  cm:
    exec.enabled: "true"

controller:
  serviceAccount:
    create: true

    annotations:
      eks.amazonaws.com/role-arn: ${ARGOCD_IRSA_ROLE_ARN}

repoServer:
  env:
    - name: AWS_REGION
      value: ap-southeast-1
