server:
  extraArgs:
    - --insecure

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    ingressClassName: alb

    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip

      # 🔥 QUAN TRỌNG: route đúng port service
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/backend-port: "80"

      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
