apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: root-app
  namespace: argocd

spec:
  project: default
  # CHinh lai theo repo
  source:
    repoURL: https://github.com/Huycon2352/Repo-app-ops.git
    targetRevision: main
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
