apiVersion: v1
kind: Secret
metadata:
  name: dev-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster

type: Opaque

stringData:
  name: dev
  # Can doi IP server lai
  server: https://172.20.0.2:6443   
  config: |
    {
      "bearerToken": "Dien token",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "Dien CA cua Cluster ket noi den"
      }
    }
