apiVersion: v1
kind: Secret

metadata:
  name: repo-private
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  # Doi repo lai neu muon
  url: https://github.com/Huycon2352/Repo-app-ops.git
  #dang nhap user, voi pat
  username: Huycon2352
  password: xxx
