name: Deploy to EKS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t hgyang25/vote-app ./vote
          docker push hgyang25/vote-app

          docker build -t hgyang25/result-app ./result
          docker push hgyang25/result-app

          docker build -t hgyang25/worker-app ./worker
          docker push hgyang25/worker-app

      - name: Setup kubectl
        run: |
          aws eks update-kubeconfig --region ap-southeast-1 --name voting-cluster

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-specifications/
