name: Terraform Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "infrastructure/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/environments/dev

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Init
      - name: Terraform Init
        run: terraform init

      # Validate (thêm bước này để check syntax)
      - name: Terraform Validate
        run: terraform validate

      # Plan (QUAN TRỌNG để debug)
      - name: Terraform Plan
        run: terraform plan

      # Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
