name: Terraform Infrastructure Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1

concurrency:
  group: terraform-infra
  cancel-in-progress: false

jobs:
  # =========================================================
  # MANAGEMENT INFRA
  # =========================================================
  management-infra:
    name: Management Infra
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/environments/management-infra

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: azure/setup-kubectl@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply -auto-approve tfplan

      # -----------------------------------------------------
      # WAIT CLUSTER ACTIVE
      # -----------------------------------------------------
      - name: Wait Cluster Active
        run: |
          aws eks wait cluster-active \
            --name management-cluster \
            --region $AWS_REGION

      # -----------------------------------------------------
      # CONNECT CLUSTER
      # -----------------------------------------------------
      - name: Connect Cluster
        run: |
          aws eks update-kubeconfig \
            --name management-cluster \
            --region $AWS_REGION

      # -----------------------------------------------------
      # WAIT NODES READY
      # -----------------------------------------------------
      - name: Wait Nodes Ready
        run: |
          kubectl wait \
            --for=condition=Ready nodes \
            --all \
            --timeout=900s

      # -----------------------------------------------------
      # WAIT COREDNS
      # -----------------------------------------------------
      - name: Wait CoreDNS
        run: |
          kubectl rollout status deployment/coredns \
            -n kube-system \
            --timeout=900s

  # =========================================================
  # MANAGEMENT ADDONS
  # =========================================================
  management-addons:
    name: Management Addons
    runs-on: ubuntu-latest

    needs: management-infra

    defaults:
      run:
        working-directory: infrastructure/environments/management-addons

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: azure/setup-kubectl@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Connect Cluster
        run: |
          aws eks update-kubeconfig \
            --name management-cluster \
            --region $AWS_REGION

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply -auto-approve tfplan

  # =========================================================
  # MANAGEMENT ARGOCD
  # =========================================================
  management-argocd:
    name: Management ArgoCD
    runs-on: ubuntu-latest

    needs:
      - management-addons

    defaults:
      run:
        working-directory: infrastructure/environments/management-argocd

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: azure/setup-kubectl@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Connect Cluster
        run: |
          aws eks update-kubeconfig \
            --name management-cluster \
            --region $AWS_REGION

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply -auto-approve tfplan

      # -----------------------------------------------------
      # WAIT ARGOCD SERVER
      # -----------------------------------------------------
      - name: Wait ArgoCD Server
        run: |
          kubectl rollout status deployment/argocd-server \
            -n argocd \
            --timeout=900s

      # -----------------------------------------------------
      # WAIT ARGOCD LOADBALANCER
      # -----------------------------------------------------
      - name: Wait ArgoCD LoadBalancer
        run: |
          for i in {1..60}; do

            HOST=$(kubectl get svc argocd-server \
              -n argocd \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ ! -z "$HOST" ]; then
              echo "LoadBalancer ready: $HOST"
              exit 0
            fi

            echo "Waiting LoadBalancer..."
            sleep 10
          done

          echo "LoadBalancer not ready"
          exit 1

      # -----------------------------------------------------
      # WAIT REPO SERVER
      # -----------------------------------------------------
      - name: Wait ArgoCD Repo Server
        run: |
          kubectl rollout status deployment/argocd-repo-server \
            -n argocd \
            --timeout=900s

      # -----------------------------------------------------
      # WAIT APPLICATION CONTROLLER
      # -----------------------------------------------------
      - name: Wait ArgoCD Application Controller
        run: |
          kubectl rollout status statefulset/argocd-application-controller \
            -n argocd \
            --timeout=900s

      # -----------------------------------------------------
      # WAIT REDIS
      # -----------------------------------------------------
      - name: Wait ArgoCD Redis
        run: |
          kubectl rollout status deployment/argocd-redis \
            -n argocd \
            --timeout=900s

  # =========================================================
  # DEV INFRA
  # =========================================================
  dev-infra:
    name: Dev Infra
    runs-on: ubuntu-latest

    needs: management-argocd

    defaults:
      run:
        working-directory: infrastructure/environments/dev_infra

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: azure/setup-kubectl@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply -auto-approve tfplan

      # -----------------------------------------------------
      # WAIT CLUSTER ACTIVE
      # -----------------------------------------------------
      - name: Wait Cluster Active
        run: |
          aws eks wait cluster-active \
            --name dev-cluster \
            --region $AWS_REGION

      # -----------------------------------------------------
      # CONNECT DEV CLUSTER
      # -----------------------------------------------------
      - name: Connect Dev Cluster
        run: |
          aws eks update-kubeconfig \
            --name dev-cluster \
            --region $AWS_REGION

      # -----------------------------------------------------
      # WAIT NODES
      # -----------------------------------------------------
      - name: Wait Nodes Ready
        run: |
          kubectl wait \
            --for=condition=Ready nodes \
            --all \
            --timeout=900s

      # -----------------------------------------------------
      # WAIT COREDNS
      # -----------------------------------------------------
      - name: Wait CoreDNS
        run: |
          kubectl rollout status deployment/coredns \
            -n kube-system \
            --timeout=900s

  # =========================================================
  # DEV ADDONS
  # =========================================================
  dev-addons:
    name: Dev Addons
    runs-on: ubuntu-latest

    needs: dev-infra

    defaults:
      run:
        working-directory: infrastructure/environments/dev-addons

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: azure/setup-kubectl@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Connect Dev Cluster
        run: |
          aws eks update-kubeconfig \
            --name dev-cluster \
            --region $AWS_REGION

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply -auto-approve tfplan

      # -----------------------------------------------------
      # WAIT METRICS SERVER
      # -----------------------------------------------------
      - name: Wait Metrics Server
        run: |
          kubectl rollout status deployment/metrics-server \
            -n kube-system \
            --timeout=900s

      # -----------------------------------------------------
      # WAIT ARGO ROLLOUTS
      # -----------------------------------------------------
      - name: Wait Argo Rollouts
        run: |
          kubectl rollout status deployment/argo-rollouts \
            -n argo-rollouts \
            --timeout=900s

      # -----------------------------------------------------
      # WAIT CLUSTER AUTOSCALER
      # -----------------------------------------------------
      - name: Wait Cluster Autoscaler
        run: |
          kubectl rollout status deployment/cluster-autoscaler-aws-cluster-autoscaler \
            -n kube-system \
            --timeout=900s

  # =========================================================
  # MANAGEMENT ARGOCD CLUSTERS
  # =========================================================
  management-argocd-clusters:
    name: Management ArgoCD Clusters
    runs-on: ubuntu-latest

    needs:
      - dev-addons

    defaults:
      run:
        working-directory: infrastructure/environments/management-argocd-clusters

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: azure/setup-kubectl@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Connect Cluster
        run: |
          aws eks update-kubeconfig \
            --name management-cluster \
            --region $AWS_REGION

      - run: terraform init

      - run: terraform validate

      - run: terraform plan -out=tfplan

      - run: terraform apply -auto-approve tfplan
