name: Terraform Infrastructure

on:
  push:
    branches: ["main"]
    paths:
      - "infrastructure/**"
  workflow_dispatch:

jobs:
  # 🔹 STEP 1: BOOTSTRAP
  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (bootstrap)
        run: terraform init
        working-directory: infrastructure/bootstrap

      - name: Terraform Apply (bootstrap)
        run: terraform apply -auto-approve
        working-directory: infrastructure/bootstrap

  # 🔹 STEP 2: EKS (phụ thuộc bootstrap)
  eks:
    runs-on: ubuntu-latest
    needs: bootstrap # 🔥 QUAN TRỌNG

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (eks)
        run: terraform init
        working-directory: infrastructure/environments/dev

      - name: Terraform Apply (eks)
        run: terraform apply -auto-approve
        working-directory: infrastructure/environments/dev
